# Generated by Django 5.1.6 on 2025-02-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('Computer Science', 'Computer Science'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Engineering', 'Engineering'), ('English', 'English'), ('Sex ED', 'Sex ED')], max_length=50, null=True),
        ),
    ]
